import type { Agent, HarnessOptions, Subagent } from "../drizzle/schema";
import { toProviderModelString, type ModelProvider } from "../shared/catalog";

type ToolLite = { slug: string; type: "builtin" | "mcp"; config?: Record<string, unknown> | null };

function py(value: string | null | undefined): string {
  const s = value ?? "";
  return JSON.stringify(s);
}

function indentBlock(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((l) => (l.length ? pad + l : l))
    .join("\n");
}

/**
 * Generate a ready-to-run Python snippet that reflects an agent's configuration
 * using create_deep_agent().
 */
export function generateAgentCode(
  agent: Agent,
  agentTools: ToolLite[],
  subagents: Subagent[]
): string {
  const harness = (agent.harness ?? {}) as Partial<HarnessOptions>;
  const modelStr = toProviderModelString(agent.modelProvider as ModelProvider, agent.model);

  const lines: string[] = [];
  lines.push("# Auto-generated by DeepFleet — reflects this agent's current configuration.");
  lines.push("# pip install deepagents");
  lines.push("from deepagents import create_deep_agent");
  if (subagents.length) lines.push("from deepagents import SubAgent");
  lines.push("");

  // tool stubs
  const builtins = agentTools.filter((t) => t.type === "builtin");
  const mcps = agentTools.filter((t) => t.type === "mcp");

  if (builtins.length) {
    lines.push("# --- Tools ---");
    for (const t of builtins) {
      const fn = t.slug.replace(/[^a-zA-Z0-9_]/g, "_");
      lines.push(`def ${fn}(query: str) -> str:`);
      lines.push(`    """${t.slug} tool — implement this for your environment."""`);
      lines.push(`    raise NotImplementedError("Wire up ${t.slug}")`);
      lines.push("");
    }
  }

  const toolRefs: string[] = builtins.map((t) => t.slug.replace(/[^a-zA-Z0-9_]/g, "_"));

  if (mcps.length) {
    lines.push("# --- Remote MCP servers ---");
    lines.push("from langchain_mcp_adapters.client import MultiServerMCPClient");
    lines.push("mcp_client = MultiServerMCPClient({");
    for (const t of mcps) {
      const url = (t.config?.serverUrl as string) ?? "https://your-mcp-server";
      const transport = (t.config?.transport as string) ?? "streamable_http";
      lines.push(`    ${py(t.slug)}: {"url": ${py(url)}, "transport": ${py(transport)}},`);
    }
    lines.push("})");
    lines.push("mcp_tools = await mcp_client.get_tools()");
    lines.push("");
    toolRefs.push("*mcp_tools");
  }

  // subagents
  if (subagents.length) {
    lines.push("# --- Subagents ---");
    lines.push("subagents = [");
    for (const s of subagents) {
      const stoolsArr = (s.tools ?? []) as string[];
      lines.push("    {");
      lines.push(`        "name": ${py(s.name)},`);
      lines.push(`        "description": ${py(s.description)},`);
      lines.push(`        "prompt": ${py(s.prompt)},`);
      if (s.model) lines.push(`        "model": ${py(s.model)},`);
      if (stoolsArr.length) lines.push(`        "tools": [${stoolsArr.map((x) => py(x)).join(", ")}],`);
      lines.push("    },");
    }
    lines.push("]");
    lines.push("");
  }

  // harness extras
  const skills = (agent.skills ?? []) as string[];
  const memory = (agent.memory ?? []) as string[];

  lines.push("# --- Agent ---");
  lines.push("agent = create_deep_agent(");
  lines.push(`    model=${py(modelStr)},`);
  lines.push(`    system_prompt=${py(agent.systemPrompt)},`);
  lines.push(`    tools=[${toolRefs.join(", ")}],`);
  if (subagents.length) lines.push("    subagents=subagents,");
  if (harness.skills && skills.length) lines.push(`    skills=[${skills.map((s) => py(s)).join(", ")}],`);
  if (harness.memory && memory.length) lines.push(`    memory=[${memory.map((m) => py(m)).join(", ")}],`);

  // interrupt_on for tools requiring approval (human-in-the-loop)
  const approvalTools = agentTools.map((t) => t.slug);
  if (approvalTools.length) {
    // Only include those needing approval; computed by caller via config, but be safe.
  }
  lines.push(`    name=${py(agent.name)},`);
  lines.push(")");
  lines.push("");
  lines.push("result = agent.invoke({\"messages\": [{\"role\": \"user\", \"content\": \"...\"}]})");
  lines.push("print(result)");

  return lines.join("\n");
}

export { indentBlock };
